### ISSUE TITLE
[Wiki] - Developers-> Detailed specification, clarification of stated tuning range

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#10]
link: [https://wiki.analog.com/university/tools/pluto/devs/specs](https://wiki.analog.com/university/tools/pluto/devs/specs)

PDF: 
[ADALM-PLUTO Detailed Specifications [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090223/ADALM-PLUTO.Detailed.Specifications.Analog.Devices.Wiki.pdf)

Tuning range is stated to be 300 MHz -3.8 GHz in the page instead of 325 MHz – 3.8 GHz which is what is stated in the Analog Website.

**Comment by mhennerich** [comment]
should be fixed
