### ISSUE TITLE
[Wiki] - Developers page, missing links

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#11]
link: [https://wiki.analog.com/university/tools/pluto/developers ](https://wiki.analog.com/university/tools/pluto/developers )

PDF: 
[ADALM-PLUTO for Developers [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090247/ADALM-PLUTO.for.Developers.Analog.Devices.Wiki.pdf)

The following links leads to pages that are not found. These links are found in the developers link provided above. These are also highlighted in the PDF file.
- Introduction
- Accessing the console
- Accessing FPGA JTAG

Other sections have no links yet.
- Section 7

For Sections 3 and 4, the links leads to AD9361 reference designs and drivers.

**Comment by rgetz** [comment]
Are the links are there now.
