### ISSUE TITLE
links on index.html are not clear

### ISSUE THREAD

**Issue by lrgetz** [analogdevicesinc/plutosdr-fw#23]
![image](https://user-images.githubusercontent.com/13320546/46116121-75df7980-c1c8-11e8-9046-88a18cf951ba.png)

Instead "check the latest version" , it should be "download the latest version", or "Download version xxx".

**Comment by tfcollins** [comment]
Yeah, that's true.

Change is added to this branch: https://github.com/analogdevicesinc/buildroot/tree/index-html-update
We need to wait for the other language updates to merge.

**Comment by rgetz** [comment]
I think this is resolved - so closing.
