### ISSUE TITLE
legal_info_html.sh doesn't try to follow 302 redirects

### ISSUE THREAD

**Issue by unixpunk** [analogdevicesinc/plutosdr-fw#26]
ncurses was giving me issues so I had to add an elif for http code 302 in scripts/legal_info_html.sh, can find changes here: https://github.com/unixpunk/plutosdr-fw/commit/5db65010a9226c5bf7f668357ec962e792b8efc6

Thanks!

**Comment by unixpunk** [comment]
I would submit a pull request but would be my first one and comparing across forks shows all my changes, which you wouldn't care about.  Let me know and I can if preferred.  Thanks!

**Comment by rgetz** [comment]
i made a comment to your commit. if that works - let us know - and i will change things here.

-robin

**Comment by unixpunk** [comment]
Thanks, left a note back there.  Here, your suggestion of grep -E "301|302" fits the bill.  Thanks!

**Comment by rgetz** [comment]
This has been fixed in the pull request #36, so closing (assuming it, or a version close will get committed to master).
