### ISSUE TITLE
[Wiki] - Prerequisites link, chipsets examples are not defined

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#3]
Prerequisites link: [https://wiki.analog.com/university/tools/pluto/users/prerequisites ](https://wiki.analog.com/university/tools/pluto/users/prerequisites )

PDF: [ADALM-PLUTO Prerequisites [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090075/ADALM-PLUTO.Prerequisites.Analog.Devices.Wiki.pdf) --> page 2 of 3

In Simple Host section, it says that "The default firmware images support the following USB chipsets". But the next statements just says chipset 1, chipset 2, and chipset 3. It was not defined and discussed what these chipsets are.

**Comment by rgetz** [comment]
https://wiki.analog.com/university/tools/pluto/prerequisites has been updated
