### ISSUE TITLE
http://192.168.2.1/LICENSE.html file is missing

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/plutosdr-fw#37]
when I go to http://192.168.2.1/ and then click on "LICENSE", I get a 404

I assume because it doesn't get copied over in post-build.sh 

${INSTALL} -D -m 0644 ${BOARD_DIR}/msd/index.html ${TARGET_DIR}/www/

but no LICENSE file. Maybe a *.html would do the trick....

**Comment by mhennerich** [comment]
Fixed with this commit:
https://github.com/analogdevicesinc/buildroot/commit/6bf0c4c148f7a4c4c2c82d85b8d8f3fe9b448202

**Comment by rgetz** [comment]
Thanks for fix
