### ISSUE TITLE
[Wiki] - End Users, examples are not yet described

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#4]
Link: [https://wiki.analog.com/university/tools/pluto/users](https://wiki.analog.com/university/tools/pluto/users)

PDF: 
[ADALM-PLUTO for End Users [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090094/ADALM-PLUTO.for.End.Users.Analog.Devices.Wiki.pdf) --> page 2 of 3

In Section 7, the examples are not yet completed or described, they are still in draft "1. example 1".

**Comment by rgetz** [comment]
All the links are live. Thanks for going through all the docs, and pointing out issues.
