### ISSUE TITLE
Date format (millisecond accuracy)

### ISSUE THREAD

**Issue by LamaBleu** [analogdevicesinc/plutosdr-fw#41]
Hi team,

Playing with timestamps, I found millisecond accuracy is not available from shell.  
Problem description and workaround here : https://github.com/LamaBleu/plutoscripts/tree/master/timems  

May you enable it for v 0.32 through busybox option : **CONFIG_FEATURE_DATE_NANO=y** ?  
Thanks a lot. Best regards.

**Comment by mhennerich** [comment]
Feature will be included in the next firmware release.
