### ISSUE TITLE
[Wiki] - End Users -> RF output link, block diagram used 

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#5]
link: [ https://wiki.analog.com/university/tools/pluto/users/transmit ]( https://wiki.analog.com/university/tools/pluto/users/transmit )

PDF: 
[ADALM-PLUTO Transmit [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090113/ADALM-PLUTO.Transmit.Analog.Devices.Wiki.pdf) 

- In this page, the block diagram used is for ad9361 and not ad9363. -> page 2 
- Following performance section link -> page 2
          The page has now content aside from the headings. However, content is only for “Data 
          Throughput (USB)” heading. There are no contents under receiver and transmitter.

**Comment by rgetz** [comment]
fixed
