### ISSUE TITLE
Attached is a PlutoSDR Firmware (0.31) with libiio 0.20

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/plutosdr-fw#51]
If you see any issues, please let me know.

[pluto.zip](https://github.com/analogdevicesinc/plutosdr-fw/files/4749223/pluto.zip)

**Comment by tfcollins** [comment]
Python functional and stress tests pass for USB and Ethernet.

**Comment by rgetz** [comment]
Thanks for testing.
