### ISSUE TITLE
build error :Incorrect selection of kernel headers: expected 4.14.x, got 4.9.x

### ISSUE THREAD

**Issue by feiger313** [analogdevicesinc/plutosdr-fw#58]
hello ,The errors I encountered in compiling：Incorrect selection of kernel headers: expected 4.14.x, got 4.9.x.
I configured the environment variables according to the information in readme.What went wrong is buildroot.

OS：ubuntu16.04.6 
vivado ：2017.4
plutosdr-fw tag:v0.32 

doc/COPYING.LGPL: OK (sha256: 5decad7e58d90d44335bf2f45ce27563bd911065c6a1a02dfa7647c4efee75c8)
>>> host-fakeroot 1.20.2 Collecting legal info
COPYING: OK (sha256: fc82ca8b6fdb18d4e3e85cfd8ab58d1bcd3f1b29abe782895abd91d64763f8e7)
>>> host-makedevs  Collecting legal info
WARNING: the Buildroot source code has not been saved
Legal info produced in /home/liuxf/work/plutosdr-fw/buildroot/output/legal-info
make[1]: Leaving directory '/home/liuxf/work/plutosdr-fw/buildroot'
scripts/legal_info_html.sh "PlutoSDR" "/home/liuxf/work/plutosdr-fw/buildroot/board/pluto/VERSIONS"
cp build/LICENSE.html buildroot/board/pluto/msd/LICENSE.html
make -C buildroot TOOLCHAIN_EXTERNAL_INSTALL_DIR= ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- BUSYBOX_CONFIG_FILE=/home/liuxf/work/plutosdr-fw/buildroot/board/pluto/busybox-1.25.0.config all
make[1]: Entering directory '/home/liuxf/work/plutosdr-fw/buildroot'
>>> toolchain-external-custom  Configuring
Incorrect selection of kernel headers: expected 4.14.x, got 4.9.x
package/pkg-generic.mk:254: recipe for target '/home/liuxf/work/plutosdr-fw/buildroot/output/build/toolchain-external-custom/.stamp_configured' failed
make[2]: *** [/home/liuxf/work/plutosdr-fw/buildroot/output/build/toolchain-external-custom/.stamp_configured] Error 1
Makefile:84: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/liuxf/work/plutosdr-fw/buildroot'
Makefile:91: recipe for target 'buildroot/output/images/rootfs.cpio.gz' failed
make: *** [buildroot/output/images/rootfs.cpio.gz] Error 2

**Comment by mhennerich** [comment]
I guess you're not building with Xilinx/SDK/2019.1 ?

michael@mhenneri-D06:/opt/Xilinx/SDK/2019.1/gnu/aarch32/lin$ cat gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr/include/linux/version.h
#define LINUX_VERSION_CODE 265728
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

That's 4.14.

You can fix your build by setting the correct toolchain headers here:
https://github.com/analogdevicesinc/buildroot/blob/a9818ab69cbe2dbbe6c3bfd1ea4634ea17699a46/configs/zynq_pluto_defconfig#L10
