### ISSUE TITLE
[Wiki] - End Users -> RF input , there's a dead link, block diagram used

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#6]
link: [https://wiki.analog.com/university/tools/pluto/users/receive ](https://wiki.analog.com/university/tools/pluto/users/receive )

PDF: 
[ADALM-PLUTO Receiver Sensitivity [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090131/ADALM-PLUTO.Receiver.Sensitivity.Analog.Devices.Wiki.pdf)

- In this page, the block diagram used is for ad9361 and not ad9363, -> page 2 
- Performance section link can also be found in this page. -> page 2
- For E4438C ESG Vector Signal Generator link, this page is not found. -> page 2

**Comment by rgetz** [comment]
fixed
