### ISSUE TITLE
Issue with buildroot busybox "error in paths"

### ISSUE THREAD

**Issue by best4username** [analogdevicesinc/plutosdr-fw#60]
> make -C buildroot TOOLCHAIN_EXTERNAL_INSTALL_DIR= ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi- BUSYBOX_CONFIG_FILE=/home/michael/devel/pluto/plutosdr-fw/buildroot/board/pluto/busybox-1.25.0.config all
> make: Entering directory '/home/black/plutosdr-fw/buildroot'
> for f in /home/michael/devel/pluto/plutosdr-fw/buildroot/board/pluto/busybox-1.25.0.config ; do if [ ! -f "${f}" ]; then printf "Kconfig fragment '%s' for '%s' does not exist\n" "${f}" "busybox"; exit 1; fi; done
> Kconfig fragment '/home/michael/devel/pluto/plutosdr-fw/buildroot/board/pluto/busybox-1.25.0.config' for 'busybox' does not exist
> make[1]: *** [package/busybox/busybox.mk:387: /home/michael/devel/pluto/plutosdr-fw/buildroot/board/pluto/busybox-1.25.0.config] Error 1
> make: *** [Makefile:84: _all] Error 2
> make: Leaving directory '/home/black/plutosdr-fw/buildroot'

I tried to search for "/home/michael/devel" by "grep -ir " to know where it come from with no luck.
All my sources is up to date and git status gives me every thing right and submodules also.

also try to understand :
https://buildroot.org/downloads/manual/manual.html#_infrastructure_for_packages_using_kconfig_for_configuration_files

Thanks in advance

**Comment by mhennerich** [comment]
Not sure why you follow these steps - Didn't you see the notice here:
https://wiki.analog.com/university/tools/pluto/building_the_image#how_does_it_work

**All these steps are automatically handled by make. They are just explained here, for those who are interested.**

Let's close this.

-Michael
