### ISSUE TITLE
[Wiki] - Receiver sensitivity, Variable not defined

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#7]
link: [https://wiki.analog.com/university/tools/pluto/users/receiver_sensitivity ](https://wiki.analog.com/university/tools/pluto/users/receiver_sensitivity )

PDF: 
[ADALM-PLUTO Receiver Sensitivity [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090137/ADALM-PLUTO.Receiver.Sensitivity.Analog.Devices.Wiki.pdf)

In the RX Noise Figure Equation, variable Na is not defined. -> page 1

**Comment by rgetz** [comment]
Fixed
