### ISSUE TITLE
Getting an error "build/system_top.xsa doesn't have supported extension"

### ISSUE THREAD

**Issue by a-nepp** [analogdevicesinc/plutosdr-fw#71]
I'm trying to build firmware with following commands:
```
 export CROSS_COMPILE=arm-linux-gnueabihf-
 export PATH=$PATH:/opt/Xilinx/SDK/2019.1/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin
 export VIVADO_SETTINGS=/opt/Xilinx/Vivado/2021.1/settings64.sh
 make
```
and I'm getting an error 
```
bash -c "source /opt/Xilinx/Vivado/2021.1/settings64.sh && xsct scripts/create_fsbl_project.tcl"
ERROR: [Hsi 55-1699] build/system_top.xsa doesn't have supported extension. Supported Hardware HandOff File extensions are .hwh, .xml, .hsm, .hdf

```

**Comment by mhennerich** [comment]
This is strange. 2019.1 used to generate and consume HDF files. Everything later uses XSA files.
For me it looks like you have different Vivado tools versions on path.

**Comment by a-nepp** [comment]
Hm, still getting the same error. Have no idea what is the problem

**Comment by mhennerich** [comment]
What version do you install?

**Comment by a-nepp** [comment]
I'm using unified 2021.1 installer for Vivado and SDK 2019.1 installer for SDK

**Comment by a-nepp** [comment]
`hsi` and `xsct` seem to only be present in Xilinx/SDK/2019.1/bin folder. Is it okay?

**Comment by mhennerich** [comment]
That might be the problem.

Only use the compiler from 2019.1...

**Comment by a-nepp** [comment]
Are this tools included in Vivado Enterprice edition? If not, how do I install them?

**Comment by a-nepp** [comment]
Are they included in Vivado Enterprice edition? If not, how do I install them?

**Comment by tfcollins** [comment]
Yes. You can install the SDK and Vivado from the same unified installer. Mixing SDK and Vivado versions should be generally avoided

**Comment by a-nepp** [comment]
You can't install 2019.1 SDK from 2021.1 installer

**Comment by tfcollins** [comment]
> You can't install 2019.1 SDK with 2021.1 installer

Thats not what I meant. You use the same installer to install the SDK and Vivado of the same version. This was the same before the "unified" installer existed. I would not expect any installer to support cross versions.
