### ISSUE TITLE
Add hook in init.d to run user application code

### ISSUE THREAD

**Issue by timbly5000** [analogdevicesinc/plutosdr-fw#74]
May I suggest adding the following script permanently:  /etc/init.d/S99autorun

#!/bin/sh
#Script to check for and run user-supplied /mnt/jffs2/startup.sh

if test -f /mnt/jffs2/autorun.sh; then
    source /mnt/jffs2/autorun.sh
fi

This is a tiny addition and will allow a stand-alone app (e.g. stored in /mnt/jffs2) to be started after boot.

Many thanks
Tim

**Comment by mhennerich** [comment]
I put it on the list for v0.36
