### ISSUE TITLE
[Wiki] - End Users -> Antennas, there's a dead link

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#8]
link: [: https://wiki.analog.com/university/tools/pluto/users/antennas](https://wiki.analog.com/university/tools/pluto/users/antennas)

PDF: 
[ADALM-PLUTO Antennas [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090153/ADALM-PLUTO.Antennas.Analog.Devices.Wiki.pdf)

A link present in the page is a dead link. [http://www.antenna-theory.com/http://antenna-theory.com](http://www.antenna-theory.com/http://antenna-theory.com), this page cannot be found. -> page 1

**Comment by rgetz** [comment]
http://antenna-theory.com/ works for me.
