### ISSUE TITLE
Problem with firmware programming via jtag

### ISSUE THREAD

**Issue by dendyKP** [analogdevicesinc/plutosdr-fw#80]
Hello!
When programming any firmware  via JTAG with the DLC10 programmer in Vivado 2020.2 the following errors occur: ERROR: [Labtools 27-3165] End of startup status: LOW
ERROR: [Common 17-39] 'program_hw_devices' failed due to earlier errors.
Does anyone know what the error might be?
![git_pluto2](https://user-images.githubusercontent.com/124365648/216611658-a8b71a48-6181-4631-956a-7c18e74d8abc.jpg)

**Comment by mhennerich** [comment]
This is more a question for a Xilinx/AMD forum
