### ISSUE TITLE
v0.36 no more USB connection

### ISSUE THREAD

**Issue by HB9IIU** [analogdevicesinc/plutosdr-fw#82]
Just wondering wether I am the only one who can now longer open 192.168.2.1 via USB after upgrade from v0.35 to v0.36.
Ethernet is ok, but no possible connection anymore via USB on Windows 11, nor Linux, or MAC
When reflashing v0.35, all normal again.
Thanks

**Comment by mhennerich** [comment]
Right - it works for me on Linux, but Windows get's a wrong IP address assigned.
I create a new release with a fix today.

**Comment by HB9IIU** [comment]
Thank you Michael

v0.37 working now
