### ISSUE TITLE
IPv6 off?

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/plutosdr-fw#87]
```
# zcat /proc/config.gz | grep -i ipv6
# CONFIG_IPV6 is not set
```
It would be nice for those who are using USB dongles to turn it on.

**Comment by mhennerich** [comment]
I'll add this for the next FW release

**Comment by mhennerich** [comment]
Completed

**Comment by hb9eue** [comment]
Hmm, on 0.38 I still get:
# zcat /proc/config.gz | grep -i ipv6
# CONFIG_IPV6 is not set

How do I enable ipv6? My router is sending out RA but my adalm pluto via ethernet usb dongle is not setting an IPv6 address.
