### ISSUE TITLE
[Wiki]- End Users-> Windows link, no content under IIO Devices

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/plutosdr-fw#9]
link: [https://wiki.analog.com/university/tools/pluto/drivers/windows ](https://wiki.analog.com/university/tools/pluto/drivers/windows )

PDF: 
[Windows Drivers [Analog Devices Wiki].pdf](https://github.com/analogdevicesinc/plutosdr-fw/files/1090183/Windows.Drivers.Analog.Devices.Wiki.pdf)

In this page, there is no information content or discussion under IIO Devices Section. -> page 6

**Comment by rgetz** [comment]
Added something
